/****************************************************************************
**
** DCOP Skeleton generated by dcopidl2cpp from KWinInterface.kidl
**
** WARNING! All changes made in this file will be lost!
**
*****************************************************************************/

#include "KWinInterface.h"

#include <kdatastream.h>


static const char* const KWinInterface_ftable[2][3] = {
    { "ASYNC", "reconfigure()", "reconfigure()" },
    { 0, 0, 0 }
};
static const int KWinInterface_ftable_hiddens[1] = {
    0,
};

bool KWinInterface::process(const QCString &fun, const QByteArray &data, QCString& replyType, QByteArray &replyData)
{
    if ( fun == KWinInterface_ftable[0][1] ) { // void reconfigure()
	replyType = KWinInterface_ftable[0][0]; 
	reconfigure( );
    } else {
	return DCOPObject::process( fun, data, replyType, replyData );
    }
    return true;
}

QCStringList KWinInterface::interfaces()
{
    QCStringList ifaces = DCOPObject::interfaces();
    ifaces += "KWinInterface";
    return ifaces;
}

QCStringList KWinInterface::functions()
{
    QCStringList funcs = DCOPObject::functions();
    for ( int i = 0; KWinInterface_ftable[i][2]; i++ ) {
	if (KWinInterface_ftable_hiddens[i])
	    continue;
	QCString func = KWinInterface_ftable[i][0];
	func += ' ';
	func += KWinInterface_ftable[i][2];
	funcs << func;
    }
    return funcs;
}


